CREATE TABLE api_keys (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    key_hash BYTEA UNIQUE NOT NULL, 
    description TEXT,
    environment TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    rate_limit_per_minute INTEGER NOT NULL DEFAULT 1000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,
    client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE
);
